cmu-db/benchbase

src/main/java/com/oltpbenchmark/benchmarks/noop/procedures/NoOp.java
This is a direct port of https://github.com/oltpbenchmark/oltpbench/pull/388
which was opened against OLTPBench after the work on BenchBase had begun.
Description from the original PR by @michaelfruth
---
The benchmark always ran through the catch-block, because
stmt.executeQuery() expects a result. The single query ';' does not
return anything at all.
Now, the query is executed and if there is a result, than it is
processed as before.
Tested with PostgreSQL 13.
See also: https://github.com/oltpbenchmark/oltpbench/pull/229
=> Fix NoOp benchmark execution.

src/main/resources/log4j.properties
The new version of HikariCP introduced by https://github.com/cmu-db/benchbase/pull/1 is very noisy.
Excerpt from tests:
```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 sec
Running com.oltpbenchmark.benchmarks.twitter.TestTwitterBenchmark
[INFO ] 2021-08-09 16:30:21,662 [main]  com.zaxxer.hikari.pool.HikariPool checkFailFast - HikariPool-100 - Added connection org.hsqldb.jdbc.JDBCConnection@6e0dec27
[INFO ] 2021-08-09 16:30:21,677 [main]  com.zaxxer.hikari.pool.HikariPool checkFailFast - HikariPool-101 - Added connection org.hsqldb.jdbc.JDBCConnection@4199761d
[INFO ] 2021-08-09 16:30:21,697 [main]  com.zaxxer.hikari.pool.HikariPool checkFailFast - HikariPool-102 - Added connection org.hsqldb.jdbc.JDBCConnection@738ae785
[INFO ] 2021-08-09 16:30:21,710 [main] …
```
=> Reduce verbosity of HikariPool logger (INFO to WARN).

pom.xml
It turns out that this is needed for `./mvnw -B release:prepare` to function properly.
=> Add SNAPSHOT to version.

src/main/java/com/oltpbenchmark/benchmarks/auctionmark/AuctionMarkLoader.java, src/main/java/com/oltpbenchmark/benchmarks/auctionmark/util/ItemId.java, src/main/java/com/oltpbenchmark/benchmarks/auctionmark/util/LoaderItemInfo.java, src/main/java/com/oltpbenchmark/benchmarks/auctionmark/util/UserId.java, src/main/java/com/oltpbenchmark/util/CompositeId.java, src/test/java/com/oltpbenchmark/benchmarks/auctionmark/util/TestUserIdGenerator.java, src/test/java/com/oltpbenchmark/util/TestCompositeIdRange.java
This is a port of https://github.com/oltpbenchmark/oltpbench/pull/320 which was written by @bglasber
The original PR description is copied below.
---
When generating an auctionmark database with a larger scale factor (e.g. 50), there are collisions in UserIds because there not enough bits allocated for OFFSET. There is some space left over in the CompositeId, so I've allocated a few more bits. Also, I've reordered the fields in UserId to match how they are packed in the compositeId. I've verified that this fix works to generate an auctionmark database with scalefactor 50.
The number of rows also exceeds the max values for short, so I've switched those to int in AuctionmarkLoader.
I propose changing the encode method on CompositeId to throw an IllegalArgumentException rather than assert. …
=> Port AuctionMark fixes for large scalefactor.

.github/workflows/maven.yml
Forgot to update the maven.yml with the SNAPSHOT version PR.
=> Update maven.yml with the right version name (2021-SNAPSHOT).

src/main/java/com/oltpbenchmark/benchmarks/tatp/TATPLoader.java
executeBatch should not be called unless addBatch was called.
---
These errors all manifest occasionally in the Java maven tests because those all use HSQLDB. Regular PostgreSQL and MySQL directly query the catalog and therefore are unaffected.
=> Fix TATPLoader for HSQLDB.

README.md, pom.xml, src/main/java/com/oltpbenchmark/DBWorkload.java, src/main/java/com/oltpbenchmark/WorkloadConfiguration.java, src/main/java/com/oltpbenchmark/api/BenchmarkModule.java, src/main/java/com/oltpbenchmark/api/LoaderThread.java, src/main/java/com/oltpbenchmark/api/Worker.java, src/main/java/com/oltpbenchmark/benchmarks/auctionmark/AuctionMarkProfile.java, src/main/java/com/oltpbenchmark/benchmarks/auctionmark/AuctionMarkWorker.java, src/main/java/com/oltpbenchmark/benchmarks/epinions/EpinionsBenchmark.java, src/main/java/com/oltpbenchmark/benchmarks/hyadapt/HYADAPTBenchmark.java, src/main/java/com/oltpbenchmark/benchmarks/seats/SEATSProfile.java, src/main/java/com/oltpbenchmark/benchmarks/seats/SEATSWorker.java, src/main/java/com/oltpbenchmark/benchmarks/sibench/SIBenchmark.java, src/main/java/com/oltpbenchmark/benchmarks/ycsb/YCSBBenchmark.java, src/main/resources/log4j.properties, src/test/java/com/oltpbenchmark/api/AbstractTestCase.java
We observed performance degradation in NoisePage (20k to 10k TPC-C, 7k to 5k TATP) when using HikariCP compared to the old "one worker maintains one persistent connection" model.
HikariCP may also muddy numbers slightly. Consider for example running TATP with 400 terminals and 12 pool size. How many clients are being served, 400 or 12?
Additionally, HikariCP introduces some performance overhead with the pool monitoring and leak detection checks. Since we're just running benchmarks with a fixed number of terminals / workers, we don't _need_ a pool (though a pool may be nice to support dynamic resizing in the future).
Given the above considerations, we propose stripping out HikariCP.
=> Strip out HikariCP.

src/main/java/com/oltpbenchmark/api/Worker.java
This PR reduces the verbosity of retry logic from WARN to DEBUG.
This PR also brings back a check for null phase (e.g., during teardown) that was accidentally removed.
=> Reduce retry verbosity. Add missing null check.

src/main/java/com/oltpbenchmark/api/Worker.java
The refactor exposed a race condition that was likely to be
hit when you had a high number of terminals, manifesting as a null
pointer exception on trying to get the phase from the state.
It isn't immediately clear where this race condition is, so we
are reverting to the old "get the state once" logic for now.
To be clear, this PR does not fix the bug, which has been around for a while.
This PR will just reduce the probability that the bug trips.
=> Revert to the old logic for post-phase checks.

docker/cockroach-latest/docker-compose.yml, docker/mysql-5/docker-compose.yml, docker/mysql-latest/docker-compose.yml, docker/postgres-latest/docker-compose.yml
updating docker files with correct database name (`benchbase` instead of `oltpbench`)
=> fix broken docker examples that reference old database name

src/main/java/com/oltpbenchmark/benchmarks/tpcc/procedures/Delivery.java, src/main/java/com/oltpbenchmark/benchmarks/tpcc/procedures/Payment.java
Fix #39.
Note that the schema types are already Decimal, so we do want to use BigDecimal.
=> Change TPC-C back to Decimal instead of Real.

src/main/resources/benchmarks/ycsb/dialect-spanner.xml
I fixed SQL syntax errors in YCSB on Spanner by adding `dialect-spanner.xml`.
Syntax error on `SELECT FOR UPDATE`:
```
[DEBUG] 2021-12-17 15:56:19,079 [YCSBWorker<000>]  com.oltpbenchmark.api.Worker doWork - Retryable SQLException occurred during [com.oltpbenchmark.benchmarks.ycsb.procedures.ReadModifyWriteRecord/06]... current retry attempt [0], max retry attempts [3], sql state [null], error code [3].
com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Syntax error: Expected end of input but got keyword FOR [at 1:44]
SELECT * FROM usertable where YCSB_KEY=@p1 FOR UPDATE
^ - Statement: 'SELECT * FROM usertable where YCSB_KEY=@p1 FOR UPDATE'
at …
```
=> Add dialect-spanner.xml for YCSB

config/cockroachdb/sample_tpcc_config.xml, config/mysql/sample_tpcc_config.xml, config/noisepage/sample_tpcc_config.xml, config/postgres/sample_tpcc_config.xml
Comment out keying and wait times for default TPC-C configs.
The keying and wait times are required by the spec;
they should be enabled for a spec-compliant run.
However, most people probably do not want this enabled by default.
For example, if you're developing a system and trying to push
as many TPC-C transactions through it as you can.
---
This PR is mostly for the benefit of people who haven't been following along (e.g., me)
and who get surprised that TPC-C numbers seem to have plummeted after #83.
=> Comment out keying and wait times for default TPC-C configs.

src/main/java/com/oltpbenchmark/Results.java, src/main/java/com/oltpbenchmark/util/ResultWriter.java
Explicitly mark throughput as throughput; introduce goodput.
This clarifies that the former requests/second number reported is a true
measure of the requests per second, i.e., it includes rejected and aborted
transactions.
Specifically, the former results string
```
Results(nanoSeconds=XXX, measuredRequests=XXX) = XXX.XXX requests/sec
```
is now of the form
```
Results(nanoSeconds=XXX, measuredRequests=XXX) = XXX.XXX requests/sec (throughput), XXX.XXX requests/sec (goodput)
```
where goodput is reported as the number of completed transactions.
We also write an additional Goodput line to the summary file generated.
=> Results formatting: explicitly mark throughput as throughput; introduce goodput.

src/main/resources/benchmarks/seats/ddl-cockroachdb.sql, src/main/resources/benchmarks/seats/dialect-cockroachdb.xml
This PR includes the following two changes to improve SEATS performance:
1. Copied the `dialect-postgres.xml` over to `dialect-cockroachdb.xml`
2. Altered and renamed the secondary index on the `flight` table
These changes, 2 in particular, yielded significant improvement in the runtime of the queries joining the `flight` and `airline` tables.
=> Two small optimizations for SEATS on CockroachDB

src/main/java/com/oltpbenchmark/api/Worker.java
Fixes bug that causes an endless loop when running into an error during query execution.
=> Fix infinite loop on retry logic on transaction failure #152

src/main/java/com/oltpbenchmark/ThreadBench.java
Noticed wrong execution of serial TPC-H benchmark due to a) state being set to WARMUP even though serial execution does not require a warm-up phase, b) workers being started right after initialization due to single-threaded execution, and c) an incorrect reset for serial after a phase has finished. This resulted in unnecessary query executions during the warm-up phase and skipped cold queries for Q1 in all phases after the first one.
-- Added a synchronized state adjustment for serial execution to set state to COLD_QUERY before workers are started.
-- Added a synchronized state adjustment when execution is reset between phases.
=> Fix serial execution start and reset.

.github/workflows/maven.yml, README.md, config/cockroachdb/sample_otmetrics_config.xml, config/mariadb/sample_otmetrics_config.xml, config/mysql/sample_otmetrics_config.xml, config/plugin.xml, config/postgres/sample_otmetrics_config.xml, config/sqlite/sample_otmetrics_config.xml, src/main/java/com/oltpbenchmark/benchmarks/otmetrics/OTMetricsBenchmark.java, src/main/java/com/oltpbenchmark/benchmarks/otmetrics/OTMetricsConstants.java, src/main/java/com/oltpbenchmark/benchmarks/otmetrics/OTMetricsLoader.java, src/main/java/com/oltpbenchmark/benchmarks/otmetrics/OTMetricsUtil.java, src/main/java/com/oltpbenchmark/benchmarks/otmetrics/OTMetricsWorker.java, src/main/java/com/oltpbenchmark/benchmarks/otmetrics/procedures/GetSessionRange.java, src/main/resources/benchmarks/otmetrics/ddl-generic.sql, src/test/java/com/oltpbenchmark/benchmarks/otmetrics/TestOTMetricsBenchmark.java, src/test/java/com/oltpbenchmark/benchmarks/otmetrics/TestOTMetricsLoader.java, src/test/java/com/oltpbenchmark/benchmarks/otmetrics/TestOTMetricsWorker.java
This was originally the "TimeseriesBenchmark" that I wrote for Project1 in the [15-799 course](https://15799.courses.cs.cmu.edu/spring2022/project1.html). I have ported it over to the latest version of BenchBase and renamed it to `otmetrics` (OtterTune Metrics). This workload is based on the internal metrics collection architecture of OtterTune and a specific query that we use to generate charts. After I merge this, @haonanw98 will add the ability to insert new observations.
https://youtu.be/ZaNFPqQ6tsQ
=> New Benchmark: OtterTune Metrics

docker/benchbase/Dockerfile, docker/benchbase/build-full-image.sh
- fixup Dockerfile test for when we don't build postgres
- show plaintext build output (makes debugging easier)
=> Docker build fixups

.github/workflows/maven.yml, docker/benchbase/Dockerfile, docker/benchbase/build-full-image.sh
Fixes #193 
containeruser `UID` `GID` fixups for when using the script to build as root.
Use `CONTAINERUSER_UID` `CONTAINERUSER_GID` instead of `UID` `GID` directly.
Allow those to be supplied as environment variable overrides (e.g. `CONTAINERUSER_UID=1234 ./build-full-image.sh`)
If not available, default to `UID` `GID` as before.
If those are `0` (root, which already exists in the container), then try
to look at the `SUDO_UID` environment variable.
Also fixes up the Dockerfile to support creating a `containeruser` with an overlapping uid (e.g. `0`) in case all of the above workarounds are insufficient.
=> Docker build as root fixups

src/main/java/com/oltpbenchmark/benchmarks/resourcestresser/ResourceStresserBenchmark.java
=> Fixing the worker's ID logic of ResourceStresser

src/main/java/com/oltpbenchmark/api/Worker.java
`ThreadBench` and `WorkloadState` rely on `WorkloadState.currentPhase` being `null` as the indicator that the benchmark is over. For example: https://github.com/cmu-db/benchbase/blob/1c43cad2a9b47611806f1e101d7e4b636ae8f105/src/main/java/com/oltpbenchmark/WorkloadState.java#L205-L206
However, `Worker` relies on `BenchmarkState.state` being `DONE` as its indicator that the benchmark is over. For example, this switch assumes that because state is still `MEASURE` that the benchmark is still running and that the result of `getCurrentPhase` is safe to access: https://github.com/cmu-db/benchbase/blob/1c43cad2a9b47611806f1e101d7e4b636ae8f105/src/main/java/com/oltpbenchmark/api/Worker.java#L288-L296
The race occurs between the previously mentioned switch in `Worker` and in `ThreadBench` where …
=> null check `postPhase` in `Worker.run` to resolve race condition at terminate

src/main/java/com/oltpbenchmark/DBWorkload.java, src/main/java/com/oltpbenchmark/WorkloadConfiguration.java, src/main/java/com/oltpbenchmark/WorkloadState.java, src/main/java/com/oltpbenchmark/api/Worker.java
[pgbench](https://www.postgresql.org/docs/current/pgbench.html) has `-c` or `--connect` flag with the following behavior:
> Establish a new connection for each transaction, rather than doing it just once per client session. This is useful to measure the connection overhead.
This PR attempts to replicate that behavior with a `newConnectionPerTxn` config option.
This might be my first BenchBase PR so please double-check me on naming/code conventions for this repo. I'll also look into the test infrastructure a bit to see how easy it is to add a test scenario for this, so consider this PR WIP for the moment.
=> Add `newConnectionPerTxn` config option and implementation

docker/benchbase/fullimage/entrypoint.sh
This is a minor tweak to the docker image entrypoint script so that pid 1 in the container becomes the java process running the benchbase jar.
This is important so that when `docker stop` or `kubectl delete` is executed and a `SIGTERM` is delivered to pid 1 in the container, the bash script is no longer responsible for handling and passing the signal on to the child processes (e.g. java).
Without this, the container runtime needs to wait for the timeout and issue a `SIGKILL` before the java process ends.
=> Fix docker entrypoint script so that it handles signals

src/main/java/com/oltpbenchmark/benchmarks/auctionmark/procedures/NewComment.java
Handles primary key conflict races by marking the transaction as a `UserAbortException` for `NewComment`s.
=> Fixup a flaky AuctionMark unit test failure

src/main/java/com/oltpbenchmark/benchmarks/auctionmark/procedures/CloseAuctions.java
The use site is:
```java
dueItemsStmt.setTimestamp(param++, startTime);
dueItemsStmt.setTimestamp(param++, endTime);
dueItemsStmt.setInt(param++, ItemStatus.OPEN.ordinal());
```
So this def looks like a mistake.
=> Fix getDueItems in auctionmark/CloseAuctions

src/main/java/com/oltpbenchmark/WorkloadConfiguration.java
Some DBMSs doesn't support transactional execution. Here I add `TRANSACTION_NONE` support as specified in JDBC.
=> Add TRANSACTION_NONE support

config/cockroachdb/sample_ycsb_config.xml, config/mariadb/sample_ycsb_config.xml, config/mysql/sample_ycsb_config.xml, config/noisepage/sample_ycsb_config.xml, config/postgres/sample_ycsb_config.xml, config/spanner/sample_ycsb_config.xml, config/sqlite/sample_ycsb_config.xml, config/sqlserver/sample_ycsb_config.xml, src/main/java/com/oltpbenchmark/benchmarks/ycsb/YCSBBenchmark.java, src/main/java/com/oltpbenchmark/benchmarks/ycsb/YCSBWorker.java
By adding this line to the config file, the client can modify the zipfian constant used by the zipfian generator in the benchmark: 
`<zipfianConstant>0.99</zipfianConstant>`
=> YCSB: customizable zipfian constant

docker/README.md, docker/benchbase/devcontainer/build-in-container.sh, docker/benchbase/fullimage/Dockerfile, docker/benchbase/run-full-image.sh, docker/build-run-benchmark-with-docker.sh, docker/mysql-5/docker-compose.yml
- Support testing server versions other that `latest` with docker compose scripts.
- Fixup user setup for mysql-5 compose config.
- Fixup some variable unset issues when running outside of the devcontainer.
=> Docker script tweaks

src/main/java/com/oltpbenchmark/benchmarks/auctionmark/AuctionMarkWorker.java, src/main/java/com/oltpbenchmark/benchmarks/auctionmark/procedures/CloseAuctions.java, src/main/resources/benchmarks/auctionmark/dialect-postgres.xml
Fix some bugs in the CloseAuctions procedure of the AuctionMark benchmark:
- Missing status in Postgres's getDueItems query, causing "The column index is out of range" type exceptions;
```java
org.postgresql.util.PSQLException: The column index is out of range: 3, number of columns: 2.
at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:70)
at org.postgresql.core.v3.SimpleParameterList.setBinaryParameter(SimpleParameterList.java:137)
at org.postgresql.jdbc.PgPreparedStatement.bindBytes(PgPreparedStatement.java:1087)
at org.postgresql.jdbc.PgPreparedStatement.setInt(PgPreparedStatement.java:322)
at com.oltpbenchmark.benchmarks.auctionmark.procedures.CloseAuctions.run(CloseAuctions.java:109)
at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeCloseAuc …
```
=> Fix CloseAuctions procedure in AuctionMark

src/main/java/com/oltpbenchmark/benchmarks/auctionmark/AuctionMarkProfile.java
After retrieving the next item id, the `getNextItemId` function increments the counter with itself, effectively doubling the amount each time. This results in an exponential growth, causing the integer to overflow in just a few iterations, later resulting in the following exception:
```java
java.lang.NumberFormatException: For input string: "0-41943040"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:668)
at java.base/java.lang.Integer.parseInt(Integer.java:786)
at com.oltpbenchmark.benchmarks.auctionmark.util.ItemId.decode(ItemId.java:62)
at com.oltpbenchmark.benchmarks.auctionmark.util.ItemId.<init>(ItemId.java:50)
at com.oltpbenchmark.benchmarks.auctionmark.util.AuctionMarkUtil.getUniqueEleme …
```
=> Fix item id assignment in AuctionMark

src/main/java/com/oltpbenchmark/benchmarks/auctionmark/AuctionMarkProfile.java
In the `updateItemQueues` function, the code iterates each item queue and calls the `addItemToProperQueue` for each item. One step this function does is remove the item from the original list, if the new status is different from the old one.
This, however, triggers a `ConcurrentModificationException` exception since we are iterating and removing concurrently from the linked list:
```java
java.util.ConcurrentModificationException
at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkProfile.updateItemQueues(AuctionMarkProfile.java:749)
at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeCloseAuctions(AuctionMarkWorker.jav …
```
=> Fix concurrent modification error in AuctionMark

src/main/java/com/oltpbenchmark/Results.java, src/main/java/com/oltpbenchmark/ThreadBench.java, src/main/java/com/oltpbenchmark/util/JSONUtil.java, src/main/java/com/oltpbenchmark/util/ResultWriter.java
=> Add elapsed and start time to json summary output

CONTRIBUTORS.md, src/main/java/com/oltpbenchmark/benchmarks/otmetrics/procedures/GetSessionRange.java
Splitting otmetrics fix from PR #379.
Fix procedure `GetSessionRange` in otmetrics, which did not explicitly close SQL statement from `getPreparedStatement`.
=> Splitting otmetrics fix from #379

CONTRIBUTORS.md, src/main/java/com/oltpbenchmark/DBWorkload.java, src/main/java/com/oltpbenchmark/api/BenchmarkModule.java, src/test/java/com/oltpbenchmark/api/AbstractTestLoader.java, src/test/resources/after-load.sql
Splitting after load functionality needed for Oracle config from PR https://github.com/cmu-db/benchbase/pull/379.
Add an after load option for benchmark configs.
Benchmark configs can add an afterload tag specifying a path to an SQL file in resources. This file will be executed after loading database. 
Tested in `AbstractTestLoad.testLoadWithAfterLoad()`
=> After load functionality with test

src/test/java/com/oltpbenchmark/api/AbstractTestCase.java
This PR addresses the issue where tests would fail if the designated port was already in use. 
```
[INFO ] 2023-10-25 07:18:47,185 [main]  com.oltpbenchmark.benchmarks.resourcestresser.TestResourceStresserBenchmark setUp - starting HSQLDB server for test [testGetTransactionType] on port [9099]
[Server@191774d6]: [Thread[HSQLDB Server @191774d6,5,main]]: run()/openServerSocket(): 
java.net.BindException: Address already in use
```
Changes:
- Modified the `setUp` method in `TestResourceStresserBenchmark` class.
- Added logic to try different ports using `ServerSocket` to find an available port.
- ~~The system will attempt up to `MAX_TRIES` to find an open port before throwing an exception.~~
- The the system will make a thorough effort in finding an available port.
=> Fix Port Binding Issue During Testing

config/mariadb/sample_templated_config.xml, config/mysql/sample_templated_config.xml, config/postgres/sample_templated_config.xml, config/sqlite/sample_templated_config.xml, config/sqlserver/sample_templated_config.xml, data/templated/example.xml, src/main/java/com/oltpbenchmark/benchmarks/templated/procedures/GenericQuery.java
Feature adds a check for UPDATE style queries and handles the execution in templated benchmarks
=> Feat: Support for "Update" type queries in Templated Benchmarks

docker/benchbase/devcontainer/build-in-container.sh
- reduce duplicate calls to `fmt` target
- skip file dedup for single profile docker image builds
=> Reduce dev rebuild times for single profile docker images

config/cockroachdb/sample_templated_config.xml, config/mariadb/sample_templated_config.xml, config/mysql/sample_templated_config.xml, config/oracle/sample_templated_config.xml, config/postgres/sample_templated_config.xml, config/sqlite/sample_templated_config.xml, config/sqlserver/sample_templated_config.xml, data/templated/example.xml
INSERT query was not working due to duplicate primary keys
Simple solutions on the query did not work for all systems
(For example _INSERT IGNORE, INSERT -- IF NOT EXISTS_).
For now I changed the table of the insert to one that does not have a primary key.
This PR tries to solve #428
=> Fix: Changed INSERT statements of templated benchmarks

src/main/java/com/oltpbenchmark/benchmarks/ycsb/YCSBWorker.java, src/main/java/com/oltpbenchmark/distributions/UniformGenerator.java
This patch changes the distribution of scan lengths in YCSB from a Zipfian distribution to a uniform distribution.
The default distribution of scan lengths in YCSB Workload E is uniform [^1] [^2] [^3]. The current implementation uses Zipfian distribution with a specified skew factor, which should be avoided for fair evaluation of scan performance.
[^1]: https://github.com/brianfrankcooper/YCSB/blob/ce3eb9/workloads/workloade#L44
[^2]: https://github.com/brianfrankcooper/YCSB/blob/ce3eb9/core/src/main/java/site/ycsb/workloads/CoreWorkload.java#L536
[^3]: https://doi.org/10.1145/1807128.1807152
=> Fix scan length distribution for YCSB

.github/workflows/maven.yml, config/sqlite/sample_chbenchmark_config.xml, config/sqlite/sample_epinions_config.xml, docker/build-run-benchmark-with-docker.sh, src/main/resources/benchmarks/chbenchmark/ddl-sqlite.sql, src/main/resources/benchmarks/chbenchmark/dialect-oracle.xml, src/main/resources/benchmarks/chbenchmark/dialect-sqlite.xml
SqlServer support will happen in #517
- ~~cockroachdb chbenchmark~~ skipping for now - see #525
=> Enable chbenchmark in most CI pipelines

.github/workflows/maven.yml, src/main/java/com/oltpbenchmark/api/BenchmarkModule.java, src/main/java/com/oltpbenchmark/util/ClassUtil.java
This was reported by #493.
Running benchmarks without packaging first fails like so:
```
mvn clean compile exec:java -P postgres -Dexec.args="-b tpcc -c config/postgres/sample_tpcc_config.xml --create=true --load=true --execute=true"
java.lang.RuntimeException: Failed to retrieve class for com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark
at com.oltpbenchmark.util.ClassUtil.getClass (ClassUtil.java:200)
at com.oltpbenchmark.util.ClassUtil.getClass (ClassUtil.java:187)
at com.oltpbenchmark.util.ClassUtil.newInstance (ClassUtil.java:112)
at com.oltpbenchmark.DBWorkload.main (DBWorkload.java:165)
at org.codehaus.mojo.exec.ExecJavaMojo.doMain (ExecJavaMojo.java:385)
at org.codehaus.mojo.exec.ExecJavaMojo.doExec (ExecJavaMojo.java:374)
at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 …
```
=> Fix mvn exec:java ClassNotFoundException

config/mysql/sample_tpch_config.xml, src/main/resources/benchmarks/tpch/ddl-mysql.sql, src/main/resources/benchmarks/tpch/postload-mysql.sql
This pull request includes changes to improve the performance of loading the TPCH database on a MySQL instance by deferring index creation to a post-load script. The most important changes include adding a new post-load script reference and removing index creation statements from the DDL script.
Performance improvements:
* [`config/mysql/sample_tpch_config.xml`](diffhunk://#diff-a48fec690069601e7837968f1848c04583a74352c5d98597f05e55794fd7cb00R17-R22): Added a reference to the new post-load script `postload-mysql.sql` to create indices after loading the database, which improves performance by nearly 30%.
Codebase simplification:
* [`src/main/resources/benchmarks/tpch/ddl-mysql.sql`](diffhunk://#diff-d0e0637fb2f0a9ee276e7046d3e142c830e9a652deb6a15afb2a1733e15d3caeL19): Removed all index …
=> Optimize TPCH DDL for faster MySQL loading
