.github/workflows/maven.yml

In #7, I forgot to rename the CI databases.

Fix missing renames in GitHub Actions.

---

src/main/java/com/oltpbenchmark/api/BenchmarkModule.java

try-with-resources tripping me up...

Fix connection leak in refreshCatalog().

---

.gitignore
src/test/java/com/oltpbenchmark/util/TestTextGenerator.java

This code was trying to check that we always generated uniquely random strings but that is not practical.

Fix random failures in TestTextGenerator 

---

src/main/java/com/oltpbenchmark/benchmarks/smallbank/SmallBankWorker.java

Fix SendPayment account.

---

docker/spanner-emulator/down.sh
docker/spanner-emulator/prune.sh
src/main/java/com/oltpbenchmark/api/Worker.java

this PR fixes bad logic in `Worker.isRetryable` where the method returned true when `sqlState` was null.

Issue 94 - fixes bad logic in Worker.isRetryable

---

README.md
pom.xml
src/main/java/com/oltpbenchmark/util/ClassUtil.java

working on allowing benchmarks to be launched/run with maven, eliminating the step of packaging the project first

working on issue #128; adding exec plugin and fixing getClass method

---

src/main/java/com/oltpbenchmark/api/Worker.java

Fix MySQL ER_LOCK_WAIT_TIMEOUT SQLState code.

---

src/main/java/com/oltpbenchmark/BenchmarkState.java
src/main/java/com/oltpbenchmark/ThreadBench.java
src/main/java/com/oltpbenchmark/types/State.java

Write result files after error

---

.devcontainer/devcontainer.json
.devcontainer/scripts/.gitattributes
.devcontainer/scripts/initializeCommand
.devcontainer/scripts/initializeCommand.cmd
.devcontainer/scripts/initializeCommand.ps1
.gitignore
docker/benchbase/devcontainer/Dockerfile
docker/benchbase/run-dev-image.sh

- use initializeComment to make sure environment files and maven cache bind mounts are present
- support building docker containers inside devcontainer

devcontainer improvements

---

docker/build-run-benchmark-with-docker.sh
docker/cockroach-latest/down.sh
docker/cockroach-latest/up.sh
docker/mariadb-latest/down.sh
docker/mariadb-latest/up.sh
docker/mysql-5/down.sh
docker/mysql-5/up.sh
docker/mysql-latest/down.sh
docker/mysql-latest/up.sh
docker/postgres-latest/down.sh
docker/postgres-latest/up.sh
docker/spanner-emulator/up.sh
docker/sqlserver-latest/down.sh
docker/sqlserver-latest/up.sh

Move into the script directory first so we can execute these from any directory.

Make docker compose scripts runnable from any directory

---

src/main/java/com/oltpbenchmark/benchmarks/epinions/EpinionsLoader.java

Ensure that there's always at least one record in the Epinions trust table

---

pom.xml

Combines a number of dependabot updates into a single PR
Closes #278
Closes #262
Closes #272
Closes #275

Various maven plugin security fixups

---

.github/dependabot.yml

Help us automate issues like #274

Add some more automated security checks

---

.github/dependabot.yml

Dependabot config fixups - specify full path to Dockerfiles

---

pom.xml

Closes #285
Closes #286
Closes #287
Closes #288
Closes #289

Combine several dependabot updates to a single PR

---

.editorconfig

EditorConfig fixups to match Google Java Style

---

src/main/java/com/oltpbenchmark/api/Worker.java
src/main/java/com/oltpbenchmark/util/SQLUtil.java

Fixes a connection error exception handler case.

Connection error handling fixups

---

README.md

Fix README to indicate that Java 21 is required

Fix README to indicate that Java 21 is required.

---

.devcontainer/devcontainer.json
docker/benchbase/README.md
docker/benchbase/devcontainer/Dockerfile
docker/benchbase/run-dev-image.sh

Fixup MAVEN_CONFIG environment variable to not collide with mvnw wrapper

---

.github/workflows/maven.yml

Enable TPC-H for MariaDB in CI
